title: LogBird Documentation
description: 기술 문서 전문가의 포트폴리오 사이트
remote_theme: just-the-docs/just-the-docs

color_scheme: light

aux_links:
  "GitHub Repository": "https://github.com/isak-2/tech-writer-docs"
